spring.datasource.url: jdbc:h2:mem:myDb;DB_CLOSE_DELAY=-1
spring.datasource.username:
spring.datasource.password:
spring.datasource.driverClassName: org.h2.Driver
spring.jpa.hibernate.ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8010/eureka}
    instance:
      preferIpAddress: true

spring:
  cloud:
    stream:
      function.definition: textSupplier;textSink;formulaSupplier;formulaSink;sourceMetadataRequestSupplier;sourceMetadataSink;sourceConvertRequestSupplier;sourceConversionSink
      bindings:
        textSink-in-0:
          destination: ocr-text-result
        textSupplier-out-0:
          destination: ocr-text-source
        formulaSink-in-0:
          destination: ocr-formula-result
        formulaSupplier-out-0:
          destination: ocr-formula-source
        sourceMetadataRequestSupplier-out-0:
          destination: source-metadata-requests
        sourceMetadataSink-in-0:
          destination: source-metadata-result
        sourceConvertRequestSupplier-out-0:
          destination: source-convert-requests
        sourceConversionSink-in-0:
          destination: source-convert-results
  minio:
    bucket: sources
  application:
    name: sources-api
  security:
    ignored: /**
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.pkasila.net/auth/realms/StudyForces
